// List of available part-photo filenames (no .jpg extension).
// Generated by scripts/gen_products.js based on public/images/products contents.
// If a file exists here, getProductImage() returns its URL, else null → ProductVisual.
export const AVAILABLE_PART_PHOTOS: readonly string[] = [
  "abs-sensor",
  "ac-compressor",
  "air-filter",
  "alternator",
  "ball-joint",
  "brake-pads",
  "drive-belt",
  "floor-mat",
  "fuel-filter",
  "ignition-coil",
  "oil-filter",
  "oxygen-sensor",
  "spark-plug",
  "thermostat",
  "timing-belt",
  "water-pump",
];

const AVAILABLE = new Set(AVAILABLE_PART_PHOTOS);

const MATCHERS: Array<[RegExp, string]> = [
  [/plaquettes?.*frein/i, "brake-pads"],
  [/disques?.*frein/i, "brake-disc"],
  [/filtre.*huile/i, "oil-filter"],
  [/filtre.*habitacle/i, "cabin-filter"],
  [/filtre.*carburant/i, "fuel-filter"],
  [/filtre.*air/i, "air-filter"],
  [/(radiateur.*clim|condenseur)/i, "ac-condenser"],
  [/radiateur/i, "radiator"],
  [/pompe.*eau/i, "water-pump"],
  [/thermostat/i, "thermostat"],
  [/amortisseur/i, "shock-absorber"],
  [/rotule/i, "ball-joint"],
  [/biellette.*stabilisat/i, "stabilizer-link"],
  [/bougie/i, "spark-plug"],
  [/bobine/i, "ignition-coil"],
  // Carrosserie patterns — photos not currently available on disk,
  // so these all fall back to ProductVisual (null). Kept here for future wiring.
  [/pare-chocs/i, "pare-chocs"],
  [/(spoiler|becquet|baguette.*chocs|bas.*caisse|d[ée]flecteur)/i, "pare-chocs"],
  [/phare/i, "headlight"],
  [/feu.*arri[èe]re/i, "taillight"],
  [/antibrouillard/i, "fog-light"],
  [/(coque.*r[ée]troviseur|r[ée]troviseur)/i, "side-mirror"],
  [/calandre/i, "calandre"],
  [/(cadre.*calandre|grille)/i, "calandre"],
  [/capot/i, "capot"],
  [/aile(\s|$)/i, "aile"],
  [/porte(\s|-)/i, "porte"],
  [/poign[ée]e/i, "door-handle"],
  [/moulure/i, "moulure"],
  [/essuie-glace/i, "wiper"],
  [/balai/i, "wiper"],
  [/pare-brise/i, "windshield"],
  [/(vitre|lunette)/i, "windshield"],
  [/joint/i, "seal"],
  // Electricity / misc
  [/capteur.*abs/i, "abs-sensor"],
  [/(capteur.*oxyg|lambda)/i, "oxygen-sensor"],
  [/compresseur.*clim/i, "ac-compressor"],
  [/courroie.*distribution/i, "timing-belt"],
  [/courroie.*accessoire/i, "drive-belt"],
  [/embrayage/i, "clutch-kit"],
  [/alternateur/i, "alternator"],
  [/d[ée]marreur/i, "starter"],
  [/tapis/i, "floor-mat"],
];

export function getProductImage(name: string, _category?: string): string | null {
  for (const [re, key] of MATCHERS) {
    if (re.test(name)) {
      if (AVAILABLE.has(key)) return `/images/products/${key}.jpg`;
      return null;
    }
  }
  return null;
}
